name: uacs_birthday_reminder
description: "UACS software development project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  awesome_notifications: ^0.8.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.11
  flutter_slidable: ^3.1.0
  http: ^1.0.0
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  yaml: ^3.1.2
dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/app_icon_ios.png"
  image_path_android: "assets/images/app_icon_android.png"
  adaptive_icon_background: "assets/images/app_icon_android_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_android_foreground.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: "images/app_background_dark.png"
  image: images/app_splash_white.png
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/language/
  generate: true
